---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01gsthm7tp2bnvtd7d61jbf1xj"
    - from: "jfmd@*"
      to: "jfmd@01gsthm8t26kx8e8vbe0qkdkse"
schema-version: 2
