version: '3'

services:
    jenkins:
      image: jenkins/jenkins
      ports: 8080:80
      ports: 50000:50000
      networks:
        - docker_network
    artifactory:
      image: artifactory
      



networks:
    docker_network: